trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  spaUrl: 'ProyectoOesia/ProyectoOesia/spa'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage:
    displayName: 'Build, tests and deploy'
    jobs:
      - job:
        displayName: 'Build, tests and deploy'
        steps:

        - task: Npm@1
          displayName: 'Install web packages'
          inputs:
            command: 'install'
            workingDir: '$(spaUrl)'
            
        - task: Npm@1
          displayName: 'Build Vue web'
          inputs:
            command: 'custom'
            workingDir: '$(spaUrl)'
            customCommand: 'run build'

        - task: NuGetToolInstaller@1
          displayName: 'Nuget restore' 

        - task: NuGetCommand@2
          displayName: 'Install api packages'
          inputs:
            restoreSolution: '$(solution)'

        - task: VSBuild@1
          displayName: 'Build api'
          inputs:
            solution: '$(solution)'
            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'

        - task: VSTest@2
          displayName: 'Test api'
          inputs:
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'

        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy application to App service on Azure'
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'SI-Azure para estudiantes(5846b118-d790-45ff-a416-db2fa5b27e6b)'
            appType: 'webApp'
            WebAppName: 'oesia'
            packageForLinux: '$(build.artifactStagingDirectory)/WebApp.zip'